### ISSUE TITLE
Question: regridding stretched grid

### ISSUE THREAD

**Issue by lfreese** [LiamBindle/sparselt#3]
Hi Liam--

I'm trying to re-grid some stretched grid simulations and am having a bit of a hard time figuring out how to do so since the input dimensions change, so its not clear to me how to input an x and y dim. I was wondering if this is possible with sparselt, or if there is a better way to work with stretched grid outputs?

Thanks!

**Comment by LiamBindle** [comment]
Hi Lyssa,

Regridding stretched grid data should be nearly identical to regridding cubed-sphere data. You can create the gridspec files for your stretched-grid with 
```shell
# See `gridspec-create sgcs --help` for details
gridspec-create sgcs 120 -s 3.0 -t 30.0 260.0   # sgcs = stretched gnomonic cubed-sphere
```
Once you have those files, you can run `ESMF_RegridWeightGen` to generate your weights for the chosen method and destination grid, followed by sparselt to apply those weights to a dataset (same procedure has [this example](https://github.com/LiamBindle/sparselt/tree/master/examples/sample_data)). Hope that makes it more clear.

Let me know if you have any issues!
Liam

**Comment by lfreese** [comment]
Thank you! This is really helpful-- I hadn't found the sgcs option in gridspec.

**Comment by LiamBindle** [comment]
Great!
